wtf:
  colors:
    border:
      focusable: cyan
      focused: white
      normal: cyan
    checked: "gray"
    highlight:
      fore: "white"
      # back: "green"
    text: "white"
    title: "white"
  grid:
    columns: [20, 20, 20, 20, 20, 20, 20, 20]
    rows: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: cyan
          odd: white
      enabled: true
      locations:
        London: "Europe/London"
        New York: "America/New York"
        Los Angeles: "America/Los Angeles"
        Honolulu: "Pacific/Honolulu"
        Tokyo: "Asia/Tokyo"
        Melbourne: "Australia/Melbourne"
        Seoul: "Asia/Seoul"
        Bangkok: "Asia/Bangkok"
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      refreshInterval: 15
      sort: "chronological"
    bittrex:
      title: "Crypto"
      colors:
        base:
          name: white
          displayName: cyan
        market:
          name: cyan
          field: white
          value: cyan
      enabled: true
      position:
        top: 1
        left: 0
        height: 8
        width: 2
      refreshInterval: 60
      summary:
        USD:
          displayName: Market
          market:
          - BTC
          - BCH
          - DASH
          - ETH
          - LTC
          - XRP
          - ZEC
          - ZRX
